# [tool.hatch...]

[env]
requires = [
  "hatch-pip-compile",
]

# [default.extra-scripts]
# pip = "{env:HATCH_UV} pip {args}"

[envs.default]
# installer = "uv"
type = "pip-compile"
pip-compile-resolver = "uv"
# lock-filename = "requirements.lock"

[envs.hatch-test]
default-args = [
  "src",
] # testスクリプトを本体と同じディレクトリに置く
#----

[version]
path = "src/cowsay_distroless/__about__.py"

[envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/cowsay_distroless tests}"

[envs.default.scripts]
main = "python src/cowsay_distroless/main.py"
